// @ts-check

import assert from "node:assert/strict"
import {readFile} from "node:fs/promises"
import {describe, expect, it} from "@velocious/testing"
import {generateDartPackage} from "../src/backends/dart.js"
import {parseDart} from "../src/frontends/dart.js"
import {generateArtifactSet, parse, SemantifoldDiagnostic} from "../index.js"

const meaning = (value) => JSON.parse(JSON.stringify(value, (key, nested) =>
  ["location", "provenance", "resolution", "sourceProvenance"].includes(key) ? undefined : nested))

describe("Dart package backend", () => {
  it("generates one deterministic three-artifact Tasks 001-005 package", async () => {
    const source = await readFile(new URL("fixtures/functions/program.ts", import.meta.url), "utf8")
    const module = parse({filename: "program.ts", language: "typescript", source})
    const first = generateDartPackage({module, sources: [{content: source, filename: "program.ts", language: "typescript"}]})
    const second = generateDartPackage({module, sources: [{content: source, filename: "program.ts", language: "typescript"}]})

    assert.deepEqual(first, second)
    expect(first.target).toEqual("dart")
    expect(first.artifacts.map(({path}) => path)).toEqual(["pubspec.yaml", "pubspec.lock", "bin/program.dart"])
    expect(first.artifacts.map(({role}) => role)).toEqual(["manifest", "manifest", "entry"])
    expect(first.artifacts.map(({mediaType}) => mediaType).slice(0, 2)).toEqual(["application/yaml", "application/yaml"])
    expect(first.artifacts[2].mediaType).toEqual("text/x-dart")
    expect(first.artifacts[0].content).toEqual("name: semantifold_generated\npublish_to: none\nenvironment:\n  sdk: 3.13.3\n")
    expect(first.artifacts[1].content).toEqual("# Generated by pub\n# See https://dart.dev/tools/pub/glossary#lockfile\npackages: {}\nsdks:\n  dart: \"3.13.3\"\n")
    expect(first.artifacts[0].provenance.kind).toEqual("synthetic")
    expect(first.artifacts[1].provenance.kind).toEqual("synthetic")
    expect(first.artifacts[2].provenance.kind).toEqual("text")
  })

  it("emits Dart formatter-canonical checked-integer support", async () => {
    const source = await readFile(new URL("fixtures/functions/program.ts", import.meta.url), "utf8")
    const module = parse({filename: "program.ts", language: "typescript", source})
    const code = /** @type {string} */ (generateDartPackage({module}).artifacts[2].content)

    assert.match(code, /if \(value < _semantifoldMinSafeInteger \|\|\n {6}value > _semantifoldMaxSafeInteger\) \{/u)
    for (const helper of ["Add", "Subtract", "Multiply", "Negate"]) {
      assert.ok(code.includes(`final _ = _semantifoldInteger${helper};`), helper)
    }
    const operatorSource = await readFile(new URL("fixtures/operators/program.ts", import.meta.url), "utf8")
    const operatorModule = parse({filename: "operators/program.ts", language: "typescript", source: operatorSource})
    const operatorCode = /** @type {string} */ (generateDartPackage({module: operatorModule}).artifacts[2].content)

    assert.match(operatorCode, /return _semantifoldIntegerAdd\(\n {6}_semantifoldIntegerNegate\(left\),\n {6}_semantifoldIntegerMultiply\(right, 2\),\n {4}\);/u)
    assert.match(operatorCode, /ordered\(right, left\)\) &&\n {6}\(!logic\(_semantifoldBoolean\(false\), _semantifoldBoolean\(true\)\)\)/u)
  })

  it("reparses only its complete canonical checked-arithmetic prefix", async () => {
    const source = await readFile(new URL("fixtures/operators/program.ts", import.meta.url), "utf8")
    const module = parse({filename: "program.ts", language: "typescript", source})
    const generated = generateDartPackage({module}).artifacts[2]
    const code = /** @type {string} */ (generated.content)

    assert.match(code, /bool _semantifoldBoolean\(bool value\)/u)
    assert.match(code, /_semantifoldBoolean\(false\)/u)
    expect(meaning(parseDart({filename: "bin/program.dart", source: code}))).toEqual(meaning(module))
    for (const changed of [
      code.replace(/^final BigInt[^\n]+\n/u, ""),
      code.replace("_semantifoldIntegerAdd", "_semantifoldIntegerAddChanged"),
      code.replace("9007199254740991", "9007199254740990"),
      code.replace("final BigInt _semantifoldMaxSafeInteger", "final BigInt _semantifoldMinSafeInteger"),
      code.replace("\nint _semantifoldIntegerAdd", "\n" + code.slice(0, code.indexOf("\nint _semantifoldIntegerAdd")) +
        "\nint _semantifoldIntegerAdd")
    ]) assert.throws(() => parseDart({filename: "forged.dart", source: changed}))
  })

  it("maps semantic tokens and marks manifests, checked support, and main scaffolding synthetic", async () => {
    const source = await readFile(new URL("fixtures/locals/program.ts", import.meta.url), "utf8")
    const module = parse({filename: "program.ts", language: "typescript", source})
    const set = generateArtifactSet({language: "dart", module, sources: [{content: source, filename: "program.ts", language: "typescript"}]})
    const entry = set.artifacts[2]

    assert.equal(entry.provenance.kind, "text")
    const {mapping, sourceMap} = entry.provenance
    const code = /** @type {string} */ (entry.content)

    assert.equal(mapping.generated.content, code)
    assert.equal(sourceMap.file, "bin/program.dart")
    assert.deepEqual(sourceMap.sourcesContent, [source])
    for (const role of ["name", "type", "operator", "callee", "literal"]) {
      assert.ok(mapping.spans.some((span) => span.mappingKind == "exact" && span.role == role), role)
    }
    for (const text of ["_semantifoldMaxSafeInteger", "void main() {"]) {
      assert.ok(mapping.spans.some((span) => span.mappingKind == "synthetic" && span.generated &&
        code.slice(span.generated.start.offset, span.generated.end.offset).includes(text)), text)
    }
    for (const artifact of set.artifacts.slice(0, 2)) {
      assert.equal(artifact.provenance.kind, "synthetic")
      assert.ok(artifact.provenance.relatedOrigins.length > 0)
    }
  })

  it("rejects malformed IR, target collisions, unsafe integers, later-task nodes, and options transactionally", async () => {
    const source = await readFile(new URL("fixtures/functions/program.ts", import.meta.url), "utf8")
    const base = parse({filename: "program.ts", language: "typescript", source})
    /** @type {((module: any) => void)[]} */
    const mutations = [
      (module) => { module.functions[0].name = "_semantifoldInteger" },
      (module) => { module.functions[0].name = "BigInt" },
      (module) => { module.functions[0].parameters[0] = null },
      (module) => { Reflect.deleteProperty(module.entryPoint.body.statements[0].expression, "resolution") },
      (module) => { module.entryPoint.body.statements[2].expression.arguments[0].value = Number.MAX_SAFE_INTEGER + 1 },
      (module) => { module.entryPoint.body.statements[2].expression.arguments[0].value = -0 },
      (module) => {
        module.functions[0].body.statements[0].expression = {
          kind: "BinaryExpression",
          left: {kind: "IntegerLiteral", location: module.location, value: Number.MAX_SAFE_INTEGER},
          location: module.location,
          operation: "IntegerAdd",
          right: {kind: "IntegerLiteral", location: module.location, value: 1},
          type: "integer"
        }
      },
      (module) => { module.functions[0].body.statements[0].expression = module.functions[0].body.statements[0] }
    ]

    for (const mutate of mutations) {
      const module = structuredClone(base)

      mutate(module)
      assert.throws(() => generateArtifactSet({language: "dart", module}), (error) =>
        error instanceof SemantifoldDiagnostic && error.code == "UNSUPPORTED_CAPABILITY" && error.language == "dart")
    }
    const collections = await readFile(new URL("fixtures/collections/program.ts", import.meta.url), "utf8")
    const collectionModule = parse({filename: "program.ts", language: "typescript", source: collections})

    assert.throws(() => generateArtifactSet({language: "dart", module: collectionModule}), (error) =>
      error instanceof SemantifoldDiagnostic && error.code == "UNSUPPORTED_CAPABILITY" && error.language == "dart")
    for (const options of [
      {filename: "program.dart"}, {filename: "lib/program.dart"}, {mapDirective: "external"},
      {mapDirective: "none"}, {sourceMapFilename: "program.dart.map"}
    ]) {
      assert.throws(() => generateArtifactSet({language: "dart", module: base, ...options}), (error) =>
        error instanceof SemantifoldDiagnostic && error.code == "UNSUPPORTED_CAPABILITY" && error.language == "dart")
    }
  })
})
