// @ts-check

import assert from "node:assert/strict"
import {readFile} from "node:fs/promises"
import {describe, expect, it} from "@velocious/testing"
import {generateDartPackage} from "../src/backends/dart.js"
import {parse} from "../index.js"

describe("Dart package backend", () => {
  it("generates one deterministic three-artifact Tasks 001-005 package", async () => {
    const source = await readFile(new URL("fixtures/functions/program.ts", import.meta.url), "utf8")
    const module = parse({filename: "program.ts", language: "typescript", source})
    const first = generateDartPackage({module, sources: [{content: source, filename: "program.ts", language: "typescript"}]})
    const second = generateDartPackage({module, sources: [{content: source, filename: "program.ts", language: "typescript"}]})

    assert.deepEqual(first, second)
    expect(first.target).toEqual("dart")
    expect(first.artifacts.map(({path}) => path)).toEqual(["pubspec.yaml", "pubspec.lock", "bin/program.dart"])
    expect(first.artifacts.map(({role}) => role)).toEqual(["manifest", "manifest", "entry"])
    expect(first.artifacts.map(({mediaType}) => mediaType).slice(0, 2)).toEqual(["application/yaml", "application/yaml"])
    expect(first.artifacts[2].mediaType).toEqual("text/x-dart")
    expect(first.artifacts[0].content).toEqual("name: semantifold_generated\npublish_to: none\nenvironment:\n  sdk: 3.13.3\n")
    expect(first.artifacts[1].content).toEqual("# Generated by pub\n# See https://dart.dev/tools/pub/glossary#lockfile\npackages: {}\nsdks:\n  dart: \"3.13.3\"\n")
    expect(first.artifacts[0].provenance.kind).toEqual("synthetic")
    expect(first.artifacts[1].provenance.kind).toEqual("synthetic")
    expect(first.artifacts[2].provenance.kind).toEqual("text")
  })
})
