// @ts-check

import assert from "node:assert/strict"
import {readFile} from "node:fs/promises"
import {describe, it} from "@velocious/testing"
import {
  generate,
  generateArtifact,
  generatedPositionFor,
  originalPositionFor,
  parse,
  parseMapping,
  spansForNode,
  spansForSymbol,
  stringifyMapping
} from "../index.js"

const targets = ["php", "ruby", "javascript", "typescript", "java"]

describe("generated source mappings", () => {
  it("returns deterministic rich and Source Map v3 artifacts without changing legacy generated bytes", async () => {
    const source = await readFile(new URL("fixtures/locals/program.ts", import.meta.url), "utf8")
    const module = parse({filename: "program.ts", language: "typescript", source})

    for (const language of targets) {
      const artifact = generateArtifact({language, module})
      const repeated = generateArtifact({language, module})

      assert.equal(artifact.code, generate({language, module}))
      assert.deepEqual(artifact, repeated)
      assert.equal(Object.isFrozen(artifact.mapping), true)
      assert.equal(Object.isFrozen(artifact.mapping.spans), true)
      assert.equal(artifact.mapping.schema, "SemantifoldMapping")
      assert.equal(artifact.mapping.version, 1)
      assert.equal(artifact.mapping.coordinateSystem, "utf16")
      assert.equal(artifact.mapping.generated.content, artifact.code)
      assert.equal(artifact.sourceMap.version, 3)
      assert.equal(artifact.sourceMap.file, artifact.filename)
      assert.deepEqual(artifact.sourceMap.sourcesContent, [source])
      assert.deepEqual(JSON.parse(JSON.stringify(artifact.mapping)), artifact.mapping)
      assert.ok(artifact.mapping.spans.some((span) => span.mappingKind == "exact"))
      assert.ok(artifact.mapping.spans.some((span) => span.mappingKind == "anchor"))
      assert.ok(artifact.mapping.spans.some((span) => span.mappingKind == "synthetic"))
    }
  })

  it("supports deterministic serialization and forward and reverse token lookups", async () => {
    const source = await readFile(new URL("fixtures/locals/program.ts", import.meta.url), "utf8")
    const module = parse({filename: "program.ts", language: "typescript", source})
    const artifact = generateArtifact({filename: "translated.rb", language: "ruby", module})
    const generatedOffset = artifact.code.lastIndexOf("select")
    const forward = originalPositionFor(artifact.mapping, {offset: generatedOffset})
    const reverse = generatedPositionFor(artifact.mapping, {
      filename: "program.ts",
      offset: source.lastIndexOf("select")
    })
    const serialized = stringifyMapping(artifact.mapping)

    assert.equal(forward.location.filename, "program.ts")
    assert.equal(forward.location.start.offset, source.lastIndexOf("select"))
    assert.equal(forward.name, "select")
    assert.ok(reverse.some((result) => result.generatedLocation.start.offset == generatedOffset))
    assert.equal(stringifyMapping(parseMapping(serialized)), serialized)

    const mutable = structuredClone(artifact.mapping)

    originalPositionFor(mutable, {offset: generatedOffset})
    mutable.spans[1].generated.start.offset++
    assert.throws(() => originalPositionFor(mutable, {offset: generatedOffset}), /cover|range/u)
  })

  it("emits map directives only when requested and only for JavaScript-family targets", async () => {
    const source = await readFile(new URL("fixtures/program.ts", import.meta.url), "utf8")
    const module = parse({filename: "program.ts", language: "typescript", source})
    const external = generateArtifact({filename: "out.js", language: "javascript", mapDirective: "external", module})
    const inline = generateArtifact({filename: "out.ts", language: "typescript", mapDirective: "inline", module})

    assert.match(external.code, /\/\/# sourceMappingURL=out\.js\.map\n$/u)
    assert.match(inline.code, /\/\/# sourceMappingURL=data:application\/json;charset=utf-8;base64,/u)
    assert.throws(() => generateArtifact({language: "php", mapDirective: "external", module}), /JavaScript|TypeScript/u)
    assert.throws(() => generateArtifact({
      language: "javascript",
      mapDirective: "external",
      module,
      sourceMapFilename: "out.js.map\nalert(1)"
    }), /single-line/u)
  })

  it("rebuilds malformed caller metadata and maps legacy and multi-source semantic modules", async () => {
    const source = await readFile(new URL("fixtures/program.ts", import.meta.url), "utf8")
    const parsed = parse({filename: "first.ts", language: "typescript", source})
    const legacy = JSON.parse(JSON.stringify(parsed, (key, value) =>
      key == "provenance" || key == "sourceProvenance" ? undefined : value))
    const legacyArtifact = generateArtifact({
      language: "java",
      module: legacy,
      sources: [{content: source, filename: "first.ts", language: "typescript"}]
    })

    assert.equal(legacyArtifact.code, generate({language: "java", module: legacy}))
    assert.deepEqual(legacyArtifact.mapping.sources.map((registered) => registered.content), [source])
    assert.equal(legacyArtifact.mapping.spans.find((span) => span.name == "difference" && span.role == "name").mappingKind, "anchor")

    const stale = structuredClone(parsed)

    stale.provenance.nodes.forEach((node) => {
      node.id = "caller-controlled"
      node.symbolId = "caller-controlled"
    })
    stale.provenance.symbols.forEach((symbol) => {
      symbol.id = "caller-controlled"
    })
    stale.provenance.nodes[0].path = "/stale"

    const repaired = generateArtifact({language: "ruby", module: stale})

    assert.equal(new Set(repaired.mapping.nodes.map((node) => node.id)).size, repaired.mapping.nodes.length)
    assert.ok(repaired.mapping.nodes.every((node) => node.id != "caller-controlled"))
    assert.ok(repaired.mapping.symbols.every((symbol) => symbol.id != "caller-controlled"))
    assert.deepEqual(repaired.mapping.sources.map((registered) => registered.content), [source])

    const malformed = structuredClone(parsed)
    const malformedName = malformed.functions[0].sourceProvenance.ranges.name

    malformedName.start.offset = source.length + 100
    malformedName.end.offset = source.length + 110
    const sanitized = generateArtifact({language: "php", module: malformed})
    const sanitizedName = sanitized.mapping.spans.find((span) => span.name == "difference" && span.role == "name")

    assert.ok(sanitizedName.origin.location.end.offset <= source.length)

    const secondSource = source.replaceAll("difference", "alternate")
    const second = parse({filename: "second.ts", language: "typescript", source: secondSource})
    const assembled = {...legacy, functions: [legacy.functions[0], second.functions[0]], provenance: undefined}
    const multi = generateArtifact({
      language: "javascript",
      module: assembled,
      sources: [
        {content: source, filename: "first.ts", language: "typescript"},
        {content: secondSource, filename: "second.ts", language: "typescript"}
      ]
    })

    assert.deepEqual(multi.mapping.sources.map((registered) => registered.filename), ["first.ts", "second.ts"])
    assert.ok(multi.mapping.spans.some((span) => span.origin.kind == "source" && span.origin.location.filename == "first.ts"))
    assert.ok(multi.mapping.spans.some((span) => span.origin.kind == "source" && span.origin.location.filename == "second.ts"))
  })

  it("queries generated ranges by canonical node and symbol identity", async () => {
    const source = await readFile(new URL("fixtures/program.ts", import.meta.url), "utf8")
    const module = parse({filename: "program.ts", language: "typescript", source})
    const artifact = generateArtifact({language: "php", module})
    const functionNode = artifact.mapping.nodes.find((node) => node.path == "/functions/0")
    const functionSymbol = artifact.mapping.symbols.find((symbol) => symbol.declarationNodeId == functionNode.id)

    assert.ok(spansForNode(artifact.mapping, functionNode.id).length > 0)
    assert.ok(spansForSymbol(artifact.mapping, functionSymbol.id).some((span) => span.name == "difference"))
    assert.throws(() => parseMapping('{"schema":"SemantifoldMapping","version":1}'), /Malformed|Expected/u)

    const stale = structuredClone(artifact.mapping)

    stale.symbols[0].location.start.offset++
    assert.throws(() => parseMapping(JSON.stringify(stale)), /Stale/u)
  })

  it("preserves validated derived and synthetic semantic origins", async () => {
    const source = await readFile(new URL("fixtures/program.ts", import.meta.url), "utf8")
    const module = parse({filename: "program.ts", language: "typescript", source})
    const functionRecord = module.functions[0].sourceProvenance
    const entryRecord = module.entryPoint.sourceProvenance
    const functionSource = functionRecord.origin
    const entrySource = entryRecord.origin

    assert.equal(functionSource.kind, "source")
    assert.equal(entrySource.kind, "source")
    functionRecord.origin = {
      kind: "derived",
      origins: [{location: functionSource.location, role: "normalized declaration", sourceId: functionSource.sourceId}]
    }
    entryRecord.origin = {
      kind: "synthetic",
      reason: "caller-assembled entry point",
      relatedOrigins: [{location: entrySource.location, role: "entry source", sourceId: entrySource.sourceId}]
    }

    const artifact = generateArtifact({language: "java", module})
    const canonicalFunction = artifact.mapping.nodes.find((node) => node.path == "/functions/0")
    const canonicalEntry = artifact.mapping.nodes.find((node) => node.path == "/entryPoint")

    assert.ok(artifact.mapping.spans.some((span) => span.nodeId == canonicalFunction.id && span.origin.kind == "derived"))
    assert.ok(artifact.mapping.spans.some((span) => span.nodeId == canonicalEntry.id && span.origin.kind == "synthetic"))
  })
})
