// @ts-check

import {unsupportedCapability} from "../diagnostic.js"
import {finalizeMapping, toSourceMapV3} from "../mapping.js"
import {emitExpression, validateBackendModule} from "./shared.js"
import {dartRuntime} from "./dart-runtime.js"
import {emitScalarType} from "./scalars.js"
import {SourceWriter} from "./writer.js"

const pubspec = "name: semantifold_generated\npublish_to: none\nenvironment:\n  sdk: 3.13.3\n"
const lockfile = "# Generated by pub\n# See https://dart.dev/tools/pub/glossary#lockfile\npackages: {}\nsdks:\n  dart: \"3.13.3\"\n"

/**
 * Emits one deterministic dependency-free Dart package candidate.
 * @param {{filename?: string, mapDirective?: unknown, module: import("../semantic/types.js").SemanticModule, sourceMapFilename?: unknown, sources?: {filename: string, content: string, language?: import("../semantic/types.js").SemanticLanguage}[]}} input Backend request.
 * @returns {{artifacts: import("../semantic/types.js").GeneratedSetArtifact[], target: string}} Candidate artifact set.
 */
export function generateDartPackage({filename, mapDirective, module, sourceMapFilename, sources}) {
  validateBackendModule(module, "dart")
  if (filename !== undefined && filename != "bin/program.dart") {
    unsupportedCapability("dart", "artifact filename other than bin/program.dart", module.location)
  }
  if (mapDirective !== undefined || sourceMapFilename !== undefined) {
    unsupportedCapability("dart", "source-map filename or directive option", module.location)
  }
  const unreadLocals = findUnreadLocals(module)
  const writer = new SourceWriter({filename: "bin/program.dart", language: "dart", module, sources})

  emitProgram(module, writer, unreadLocals)
  const mapping = finalizeMapping(writer.finish())
  const root = mapping.nodes.find(({path}) => path == "")

  if (!root) throw new Error("Validated Dart module omitted its canonical root provenance.")
  const relatedOrigins = relatedRootOrigins(root)

  return {
    artifacts: [{
      content: pubspec,
      contentKind: "text",
      mediaType: "application/yaml",
      ownership: "generated",
      path: "pubspec.yaml",
      provenance: {
        kind: "synthetic",
        reason: "Fixed dependency-free Dart 3.13.3 package configuration.",
        relatedOrigins
      },
      role: "manifest"
    }, {
      content: lockfile,
      contentKind: "text",
      mediaType: "application/yaml",
      ownership: "generated",
      path: "pubspec.lock",
      provenance: {
        kind: "synthetic",
        reason: "Deterministic Dart pub lockfile for a package with no dependencies.",
        relatedOrigins
      },
      role: "manifest"
    }, {
      content: mapping.generated.content,
      contentKind: "text",
      mediaType: "text/x-dart",
      ownership: "generated",
      path: "bin/program.dart",
      provenance: {kind: "text", mapping, sourceMap: toSourceMapV3(mapping)},
      role: "entry"
    }],
    target: "dart"
  }
}

/**
 * Emits the compiler-owned prefix and one complete program.
 * @param {import("../semantic/types.js").SemanticModule} module Semantic module.
 * @param {SourceWriter} writer Source-aware writer.
 * @param {Set<import("../semantic/types.js").LocalDeclaration>} unreadLocals Locals requiring an analyzer-only read.
 * @returns {void}
 */
function emitProgram(module, writer, unreadLocals) {
  writer.synthetic(dartRuntime, "Checked Dart safe-integer support", [module], [""])
  for (let index = 0; index < module.functions.length; index += 1) {
    const declaration = module.functions[index]
    const path = `/functions/${index}`

    writer.synthetic("\n", "declaration separator", [declaration], [path])
    writer.mapped(emitScalarType("dart", declaration.returnType), {
      mappingKind: "exact", node: declaration.returnType, path: `${path}/returnType`, role: "type"
    })
    writer.synthetic(" ", "declaration spacing", [declaration], [path])
    writer.mapped(declaration.name, {mappingKind: "exact", node: declaration, path, role: "name"})
    const flatParameters = declaration.parameters.map((parameter) =>
      `${emitScalarType("dart", parameter.type)} ${parameter.name}`).join(", ")
    const multilineParameters = declaration.parameters.length > 0 &&
      writer.column - 1 + `(${flatParameters}) {`.length > 80

    writer.mapped("(", {mappingKind: "anchor", node: declaration, path})
    declaration.parameters.forEach((parameter, parameterIndex) => {
      const parameterPath = `${path}/parameters/${parameterIndex}`

      if (multilineParameters) {
        writer.synthetic(`${parameterIndex ? "" : "\n"}  `, "Dart parameter indentation", [parameter], [parameterPath])
      } else if (parameterIndex) writer.synthetic(", ", "parameter separator", [parameter], [parameterPath])
      writer.mapped(emitScalarType("dart", parameter.type), {
        mappingKind: "exact", node: parameter.type, path: `${parameterPath}/type`, role: "type"
      })
      writer.synthetic(" ", "parameter spacing", [parameter], [parameterPath])
      writer.mapped(parameter.name, {mappingKind: "exact", node: parameter, path: parameterPath, role: "name"})
      if (multilineParameters) writer.synthetic(",\n", "Dart formatter parameter separator", [parameter], [parameterPath])
    })
    writer.mapped(")", {mappingKind: "anchor", node: declaration, path})
    writer.synthetic(" ", "body spacing", [declaration], [path])
    writer.mapped("{", {mappingKind: "anchor", node: declaration.body, path: `${path}/body`})
    writer.synthetic("\n", "line break", [declaration], [path])
    emitBlock(writer, declaration.body, "  ", `${path}/body`, unreadLocals)
    writer.mapped("}", {mappingKind: "anchor", node: declaration.body, path: `${path}/body`})
    writer.synthetic("\n", "line break", [declaration], [path])
  }
  writer.synthetic("\nvoid main() {\n", "Dart generated main scaffold", [module.entryPoint], ["/entryPoint"])
  emitBlock(writer, module.entryPoint.body, "  ", "/entryPoint/body", unreadLocals)
  writer.synthetic("}\n", "Dart generated main scaffold", [module.entryPoint], ["/entryPoint"])
}

/**
 * Emits one ordered semantic block.
 * @param {SourceWriter} writer Source-aware writer.
 * @param {import("../semantic/types.js").Block} block Semantic block.
 * @param {string} indent Current indentation.
 * @param {string} path Exact semantic path.
 * @param {Set<import("../semantic/types.js").LocalDeclaration>} unreadLocals Locals requiring an analyzer-only read.
 * @returns {void}
 */
function emitBlock(writer, block, indent, path, unreadLocals) {
  block.statements.forEach((statement, index) =>
    emitStatement(writer, statement, indent, `${path}/statements/${index}`, unreadLocals))
}

/**
 * Emits one Tasks 001-005 statement.
 * @param {SourceWriter} writer Source-aware writer.
 * @param {import("../semantic/types.js").Statement} statement Semantic statement.
 * @param {string} indent Current indentation.
 * @param {string} path Exact semantic path.
 * @param {Set<import("../semantic/types.js").LocalDeclaration>} unreadLocals Locals requiring an analyzer-only read.
 * @returns {void}
 */
function emitStatement(writer, statement, indent, path, unreadLocals) {
  writer.synthetic(indent, "indentation", [statement], [path])
  if (statement.kind == "LocalDeclaration") {
    if (!statement.mutable) writer.mapped("final", {mappingKind: "anchor", node: statement, path})
    else writer.mapped(emitScalarType("dart", statement.type), {
      mappingKind: "exact", node: statement.type, path: `${path}/type`, role: "type"
    })
    writer.synthetic(" ", "local spacing", [statement], [path])
    if (!statement.mutable) {
      writer.mapped(emitScalarType("dart", statement.type), {
        mappingKind: "exact", node: statement.type, path: `${path}/type`, role: "type"
      })
      writer.synthetic(" ", "local spacing", [statement], [path])
    }
    writer.mapped(statement.name, {mappingKind: "exact", node: statement, path, role: "name"})
    writer.synthetic(" ", "assignment spacing", [statement], [path])
    writer.mapped("=", {mappingKind: "exact", node: statement, path, role: "operator"})
    writer.synthetic(" ", "assignment spacing", [statement], [path])
    emitExpression(writer, statement.initializer, `${path}/initializer`, "dart", identity)
    writer.mapped(";", {mappingKind: "anchor", node: statement, path})
    writer.synthetic("\n", "line break", [statement], [path])
    if (unreadLocals.has(statement)) {
      writer.synthetic(`${indent}_semantifoldUse(${statement.name});\n`, "Dart analyzer unread-local use", [statement], [path])
    }
    return
  }
  if (statement.kind == "AssignmentStatement") {
    writer.mapped(statement.target.name, {mappingKind: "exact", node: statement.target, path: `${path}/target`, role: "name"})
    writer.synthetic(" ", "assignment spacing", [statement], [path])
    writer.mapped("=", {mappingKind: "exact", node: statement, path, role: "operator"})
    writer.synthetic(" ", "assignment spacing", [statement], [path])
    emitExpression(writer, statement.expression, `${path}/expression`, "dart", identity)
    writer.mapped(";", {mappingKind: "anchor", node: statement, path})
    writer.synthetic("\n", "line break", [statement], [path])
    return
  }
  if (statement.kind == "IfStatement") return emitIf(writer, statement, indent, path, unreadLocals)
  if (statement.kind == "ReturnStatement") {
    writer.mapped("return", {mappingKind: "anchor", node: statement, path})
    if (statement.expression) {
      writer.synthetic(" ", "return spacing", [statement], [path])
      emitExpression(writer, statement.expression, `${path}/expression`, "dart", identity)
    }
    writer.mapped(";", {mappingKind: "anchor", node: statement, path})
    writer.synthetic("\n", "line break", [statement], [path])
    return
  }
  if (statement.kind == "PrintStatement") {
    writer.mapped("print", {mappingKind: "anchor", node: statement, path})
    writer.mapped("(", {mappingKind: "anchor", node: statement, path})
    emitExpression(writer, statement.expression, `${path}/expression`, "dart", identity)
    writer.mapped(");", {mappingKind: "anchor", node: statement, path})
    writer.synthetic("\n", "line break", [statement], [path])
    return
  }
  if (statement.kind == "ExpressionStatement") {
    emitExpression(writer, statement.expression, `${path}/expression`, "dart", identity)
    writer.mapped(";", {mappingKind: "anchor", node: statement, path})
    writer.synthetic("\n", "line break", [statement], [path])
    return
  }
  throw new TypeError("Unsupported Dart statement reached emission after preflight.")
}

/**
 * Emits one strict Boolean conditional.
 * @param {SourceWriter} writer Source-aware writer.
 * @param {import("../semantic/types.js").IfStatement} statement Conditional.
 * @param {string} indent Current indentation.
 * @param {string} path Exact semantic path.
 * @param {Set<import("../semantic/types.js").LocalDeclaration>} unreadLocals Locals requiring an analyzer-only read.
 * @returns {void}
 */
function emitIf(writer, statement, indent, path, unreadLocals) {
  writer.mapped("if", {mappingKind: "anchor", node: statement, path})
  writer.synthetic(" (", "Dart conditional scaffold", [statement], [path])
  emitExpression(writer, statement.condition, `${path}/condition`, "dart", identity)
  writer.synthetic(") ", "Dart conditional scaffold", [statement], [path])
  writer.mapped("{", {mappingKind: "anchor", node: statement.consequent, path: `${path}/consequent`})
  writer.synthetic("\n", "line break", [statement], [path])
  emitBlock(writer, statement.consequent, `${indent}  `, `${path}/consequent`, unreadLocals)
  writer.synthetic(indent, "indentation", [statement], [path])
  writer.mapped("}", {mappingKind: "anchor", node: statement.consequent, path: `${path}/consequent`})
  if (statement.alternate) {
    writer.synthetic(" else ", "Dart alternate scaffold", [statement], [path])
    writer.mapped("{", {mappingKind: "anchor", node: statement.alternate, path: `${path}/alternate`})
    writer.synthetic("\n", "line break", [statement], [path])
    emitBlock(writer, statement.alternate, `${indent}  `, `${path}/alternate`, unreadLocals)
    writer.synthetic(indent, "indentation", [statement], [path])
    writer.mapped("}", {mappingKind: "anchor", node: statement.alternate, path: `${path}/alternate`})
  }
  writer.synthetic("\n", "line break", [statement], [path])
}

/**
 * Finds scalar locals that Dart would diagnose because no semantic expression reads them.
 * @param {import("../semantic/types.js").SemanticModule} module Validated semantic module.
 * @returns {Set<import("../semantic/types.js").LocalDeclaration>} Unread declaration identities.
 */
function findUnreadLocals(module) {
  /** @type {Set<import("../semantic/types.js").LocalDeclaration>} */
  const unread = new Set()

  for (const root of [...module.functions.map(({body}) => body), module.entryPoint.body]) {
    /** @type {import("../semantic/types.js").LocalDeclaration[]} */
    const declarations = []
    /** @type {Set<string>} */
    const reads = new Set()

    visitStatements(root, (statement) => {
      if (statement.kind == "LocalDeclaration") {
        declarations.push(statement)
        collectIdentifierReads(statement.initializer, reads)
      } else if (statement.kind == "IfStatement") collectIdentifierReads(statement.condition, reads)
      else if (statement.kind == "AssignmentStatement" || statement.kind == "ExpressionStatement" ||
        statement.kind == "PrintStatement" || statement.kind == "ReturnStatement") {
        if (statement.expression) collectIdentifierReads(statement.expression, reads)
      }
    })
    for (const declaration of declarations) if (!reads.has(declaration.name)) unread.add(declaration)
  }
  return unread
}

/**
 * Visits every Tasks 001-005 statement in one semantic body.
 * @param {import("../semantic/types.js").Block} block Semantic block.
 * @param {(statement: import("../semantic/types.js").Statement) => void} callback Statement visitor.
 * @returns {void}
 */
function visitStatements(block, callback) {
  for (const statement of block.statements) {
    callback(statement)
    if (statement.kind == "IfStatement") {
      visitStatements(statement.consequent, callback)
      if (statement.alternate) visitStatements(statement.alternate, callback)
    }
  }
}

/**
 * Collects identifier reads without treating assignment targets as reads.
 * @param {import("../semantic/types.js").Expression} expression Semantic expression.
 * @param {Set<string>} reads Collected binding names.
 * @returns {void}
 */
function collectIdentifierReads(expression, reads) {
  if (expression.kind == "IdentifierExpression") reads.add(expression.name)
  else if (expression.kind == "CallExpression") {
    for (const argument of expression.arguments) collectIdentifierReads(argument, reads)
  } else if (expression.kind == "UnaryExpression") collectIdentifierReads(expression.operand, reads)
  else if (expression.kind == "BinaryExpression") {
    collectIdentifierReads(expression.left, reads)
    collectIdentifierReads(expression.right, reads)
  }
}

/**
 * Converts root provenance to artifact-level related origins.
 * @param {import("../semantic/types.js").SemanticNodeProvenance} root Root provenance.
 * @returns {import("../semantic/types.js").RelatedOrigin[]} Related roots.
 */
function relatedRootOrigins(root) {
  if (root.origin.kind == "source") {
    return [{location: root.origin.location, nodeId: root.id, role: "module", sourceId: root.origin.sourceId}]
  }
  const origins = root.origin.kind == "derived" ? root.origin.origins : root.origin.relatedOrigins

  return origins.map((origin) => ({...origin, nodeId: origin.nodeId ?? root.id, role: origin.role ?? "module"}))
}

/**
 * Returns one prevalidated Dart identifier unchanged.
 * @param {string} name Validated identifier.
 * @returns {string} Same identifier.
 */
function identity(name) {
  return name
}
