// @ts-check

/** Qualified edition-2021 support. Every token is checked by the Rust frontend before collapse. */
export const rustRuntime = `#![allow(dead_code, unused_variables, unused_mut, unused_assignments, unused_parens, unconditional_recursion, non_snake_case)]
fn semantifold_print_integer(value: i64) { println!("{}", value); }
fn semantifold_print_boolean(value: bool) { println!("{}", value); }
fn semantifold_print_string(value: String) { println!("{}", value); }
fn semantifold_integer_add(left: i64, right: i64) -> i64 {
    let (result, overflow): (i64, bool) = left.overflowing_add(right);
    if overflow { eprintln!("semantifold: integer overflow"); std::process::exit(70); }
    return result;
}
fn semantifold_integer_subtract(left: i64, right: i64) -> i64 {
    let (result, overflow): (i64, bool) = left.overflowing_sub(right);
    if overflow { eprintln!("semantifold: integer overflow"); std::process::exit(70); }
    return result;
}
fn semantifold_integer_multiply(left: i64, right: i64) -> i64 {
    let (result, overflow): (i64, bool) = left.overflowing_mul(right);
    if overflow { eprintln!("semantifold: integer overflow"); std::process::exit(70); }
    return result;
}
fn semantifold_integer_negate(value: i64) -> i64 {
    let (result, overflow): (i64, bool) = value.overflowing_neg();
    if overflow { eprintln!("semantifold: integer overflow"); std::process::exit(70); }
    return result;
}
`

/** Actual manifest qualified with Cargo 1.98.1 on Ubuntu 24.04 and 26.04. */
export const rustManifest = '[package]\nname = "semantifold-generated"\nversion = "0.0.0"\nedition = "2021"\nrust-version = "1.98.1"\npublish = false\nbuild = false\n\n[profile.dev]\noverflow-checks = true\npanic = "abort"\n\n[profile.release]\noverflow-checks = true\npanic = "abort"\n'

/** Cargo-generated bytes, SHA-256 185a41f6648ef49c8e7721f3321604abf05fae11c7007f823121c17fe48eec64. */
export const rustLockfile = '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "semantifold-generated"\nversion = "0.0.0"\n'
